require('dotenv').config();
const { SERVER_PORT } = process.env;
const ctrl = require('./controller');
const express = require('express');
const app = express();
app.use(express.json());
app.use(express.static(`${__dirname}/../public/assets`));
app.use(express.static(`${__dirname}/../build`));
app.post('/api/message', ctrl.message);
app.get('/api/recipe/category', ctrl.getRecipeCategories);
app.get('/api/recipe/featured', ctrl.getFeaturedRecipes);
app.get('/api/recipe/name', ctrl.getRecipeByName);
app.get('/api/ingredient/category', ctrl.getIngredientCategories);
app.get('/api/ingredient', ctrl.getIngredients);
app.get('/api/hero', ctrl.getHeroData);
app.get('/api/data', ctrl.getData);
app.listen(SERVER_PORT, () => console.log(`Portfolio running on ${SERVER_PORT}`));